# Generated by Django 4.0.3 on 2022-05-17 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pedidos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='linea_pedido',
            old_name='create_at',
            new_name='created_at',
        ),
    ]
